version: "3.8"

services:

#Backend
  treasurejunk:
    container_name: treasurejunk
    build: ./backend/database_service
    ports:
      - "8001:8001"

  product_service:
    container_name: treasurejunk_product_service
    build: ./backend/product_service
    ports:
      - "8000:8000"
    depends_on:
      - treasurejunk

#Frontend
  react_app:
    container_name: react
    build: ./frontend
    ports:
      - "3000:3000"